projects:
  businessProfile:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: uw7smugymvh7hmnzjhe3dk6o6u
      endpoints:
        prod: >-
          https://3sflb2u6lrftzd2h2rbauqap74.appsync-api.us-east-1.amazonaws.com/graphql
