projects:
  csc47300project:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: bika4jvhgzhr5n6ljlkwq2mn3u
      endpoints:
        prod: >-
          https://5iypexetybf3rd5mypwqgtxdku.appsync-api.us-east-1.amazonaws.com/graphql
