projects:
  csc47300project:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: rqcqoiugtfc4rojzbb3qat4i5i
      endpoints:
        prod: >-
          https://edppfkslznbufp4xnm5wzhqic4.appsync-api.us-east-1.amazonaws.com/graphql
