projects:
  csc47300project:
    schemaPath: src\graphql\schema.json
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: dl55e7p2cfcl7ezv5pu6rhpvh4
      endpoints:
        prod: >-
          https://i25j4orj3jfqvodvs5ouy553tu.appsync-api.us-east-1.amazonaws.com/graphql
