projects:
  csc47300project:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: f34tyabmn5c6bkm6ogwvn2cwmu
      endpoints:
        prod: >-
          https://zyvw5ohf4bhszbo37ugpwmb46m.appsync-api.us-east-2.amazonaws.com/graphql
