projects:
  csc47300project:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: kf3qgto5gjca3m2xblf7outipe
      endpoints:
        prod: >-
          https://qr2ix4jrrvbqpnmjnkvmolxj74.appsync-api.us-east-1.amazonaws.com/graphql
